apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollive

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-init-configmap.yaml
  - nats.yaml
  - postgres.yaml
  - observability-service.yaml
  - chat-service.yaml
  - dashboard-ui.yaml
  - chat-ui.yaml
  - ingress.yaml

images:
  - name: ollive-assignment-chat-service
    newName: ollive-assignment-chat-service
    newTag: latest
  - name: ollive-assignment-observability-service
    newName: ollive-assignment-observability-service
    newTag: latest
  - name: ollive-assignment-chat-ui
    newName: ollive-assignment-chat-ui
    newTag: latest
  - name: ollive-assignment-dashboard-ui
    newName: ollive-assignment-dashboard-ui
    newTag: latest
